# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "002f5cb1c332d28da153f7730b3fc2e3"
name = "prohibited-product"
handle = "prohibited-product"
application_url = "https://inquire-issue-connect-obtained.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "racreateapp.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://inquire-issue-connect-obtained.trycloudflare.com/auth/callback",
  "https://inquire-issue-connect-obtained.trycloudflare.com/auth/shopify/callback",
  "https://inquire-issue-connect-obtained.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
